<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Aleksandar" failures="4" tests="6" name="UserRegistrationTest2-FF" time="29.714" errors="0" timestamp="2021-09-15T11:55:58 CEST">
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeSignUpTests" name="verifyUnsuccessfulSignUpAction" time="0.586"/>
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeSignUpTests" name="verifyUnsuccessfulSignUpAction" time="0.648"/>
  <testcase classname="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests" name="verifySuccessfulSignUpActionChrome" time="0.52">
    <failure type="java.lang.AssertionError" message="expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]">
      <![CDATA[java.lang.AssertionError: expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpAction(PositiveSignUpTests.java:49)
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpActionChrome(PositiveSignUpTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifySuccessfulSignUpActionChrome -->
  <testcase classname="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests" name="verifySuccessfulSignUpActionChrome" time="0.521">
    <failure type="java.lang.AssertionError" message="expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]">
      <![CDATA[java.lang.AssertionError: expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpAction(PositiveSignUpTests.java:49)
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpActionChrome(PositiveSignUpTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifySuccessfulSignUpActionChrome -->
  <testcase classname="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests" name="verifySuccessfulSignUpActionFirefox" time="0.599">
    <failure type="java.lang.AssertionError" message="expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]">
      <![CDATA[java.lang.AssertionError: expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpAction(PositiveSignUpTests.java:49)
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpActionFirefox(PositiveSignUpTests.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifySuccessfulSignUpActionFirefox -->
  <testcase classname="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests" name="verifySuccessfulSignUpActionFirefox" time="0.607">
    <failure type="java.lang.AssertionError" message="expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]">
      <![CDATA[java.lang.AssertionError: expected [User has been successfully registered.] but found [Oops! There is already a user registered with the email provided.]
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpAction(PositiveSignUpTests.java:49)
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfulSignUpActionFirefox(PositiveSignUpTests.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifySuccessfulSignUpActionFirefox -->
</testsuite> <!-- UserRegistrationTest2-FF -->
