<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="SIXNS289" failures="1" tests="1" name="PositiveLoginUsernameOnMainPageTest-FF" time="12.018" errors="0" timestamp="2021-09-10T14:12:34 CEST">
  <testcase classname="local.HLVTestApp.loginandsignuptests.PositiveLoginTests" name="verifySuccessfullLoginActionOnMainPage" time="0.826">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&amp;amp;password=testPassword1]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=testPassword1]
at local.HLVTestApp.loginandsignuptests.PositiveLoginTests.verifySuccessfullLoginActionOnMainPage(PositiveLoginTests.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifySuccessfullLoginActionOnMainPage -->
  <testcase classname="local.HLVTestApp.loginandsignuptests.PositiveLoginTests" name="verifySuccessfullLoginActionOnLoginPage" time="0.0">
    <ignored/>
  </testcase> <!-- verifySuccessfullLoginActionOnLoginPage -->
</testsuite> <!-- PositiveLoginUsernameOnMainPageTest-FF -->
